# Generated by Django 6.1 on 2026-08-13 12:42

import django.contrib.postgres.constraints
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('start_datetime__lt', models.F('end_datetime'))), name='reservation_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), expressions=[('resource', '='), (models.Func(models.F('start_datetime'), models.F('end_datetime'), function='TSTZRANGE'), '&&')], name='prevent_overlapping_active_reservations'),
        ),
    ]
