# Generated by Django 6.1 on 2026-08-26 06:14

import apps.resources.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a photo of this item (jpg, jpeg, png, or webp, under 5MB). Recommended: a clear shot on a plain background, landscape orientation.', null=True, upload_to='resources/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), apps.resources.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional: link to a photo hosted elsewhere. Only used if no photo is uploaded above.', max_length=500),
        ),
    ]
